export const ORDER_SAVE_SEND_COUNTRY = "ORDER_SAVE_SEND_COUNTRY"
export const ORDER_AMOUNT = "ORDER_AMOUNT"
export const SAVE_RECIPIENT_ADDRESS = "SAVE_RECIPIENT_ADDRESS"
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"
export const SAVE_COLLECTION_METHOD = "SAVE_COLLECTION_METHOD"

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_PAYOUT_REQUEST = 'ORDER_PAYOUT_REQUEST'
export const ORDER_PAYOUT_SUCCESS = 'ORDER_PAYOUT_SUCCESS'
export const ORDER_PAYOUT_FAIL = 'ORDER_PAYOUT_FAIL'

